-- INSERT INTO companies (id, name) VALUES 
-- (1, 'Tech Innovators Inc.'),
-- (2, 'Health Solutions Ltd.'),
-- (3, 'Finance Gurus LLC'),
-- (4, 'EduTech Partners'),
-- (5, 'Green Energy Co.'),
-- (6, 'Retail Giants'),
-- (7, 'Travel Experts'),
-- (8, 'Foodies United'),
-- (9, 'Media Masters'),
-- (10, 'Auto Dynamics'),
-- (11, 'Fashion Forward'),
-- (12, 'Real Estate Pros'),
-- (13, 'Consulting Champs'),
-- (14, 'Logistics Leaders'),
-- (15, 'Entertainment Hub'),
-- (16, 'NonProfit Heroes'),
-- (17, 'Agriculture Allies'),
-- (18, 'Telecom Titans'),
-- (19, 'Pharma Pioneers'),
-- (20, 'Construction Crew'),
-- (21, 'Aerospace Aces'),
-- (22, 'Cybersecurity Squad'),
-- (23, 'AI Innovators'),
-- (24, 'Blockchain Builders'),
-- (25, 'Cloud Computing Co.'),
-- (26, 'Big Data Experts'),
-- (27, 'IoT Integrators'),
-- (28, 'VR Visionaries'),
-- (29, 'AR Architects'),
-- (30, 'Robotics Rulers'),
-- (31, '3D Printing Pros'),
-- (32, 'Quantum Quest'),
-- (33, 'Space Explorers'),
-- (34, 'Renewable Resources Inc.'),
-- (35, 'Smart Home Solutions'),
-- (36, 'Wearable Tech Co.'),
-- (37, 'E-commerce Experts'),
-- (38, 'Digital Marketing Masters'),
-- (39, 'Social Media Strategists'),
-- (40, 'Content Creators Inc.'),
-- (41, 'SEO Specialists'),
-- (42, 'PPC Professionals'),
-- (43, 'Email Marketing Experts'),
-- (44, 'Affiliate Marketing Co.'),
-- (45, 'Influencer Agency'),
-- (46, 'Web Development Wizards'),
-- (47, 'App Development Aces'),
-- (48, 'Game Development Gurus'),
-- (49, 'UI/UX Designers Inc.'),
-- (50, 'Graphic Design Group');

-- INSERT INTO business_accounts (id, email, password, first_name, last_name, account_type, company_id, created_at) VALUES 
-- (1, 'emailone@email.com', 'Password', 'John', 'Doe', 'ADMIN', 1, NOW()),
-- (2, 'email2@email.com', 'Password', 'Jane', 'Smith', 'ADMIN', 2, NOW()),
-- (3, 'emailthree@email.com', 'Password', 'Mike', 'Johnson', 'ADMIN', 3, NOW()),
-- (4, 'emailfour@email.com', 'Password', 'Sarah', 'Wilson', 'ADMIN', 4, NOW()),
-- (5, 'emailfive@email.com', 'Password', 'David', 'Brown', 'ADMIN', 5, NOW()),
-- (6, 'emailsix@email.com', 'Password', 'Lisa', 'Davis', 'ADMIN', 6, NOW()),
-- (7, 'emailseven@email.com', 'Password', 'James', 'Miller', 'ADMIN', 7, NOW()),
-- (8, 'emaileight@email.com', 'Password', 'Maria', 'Garcia', 'ADMIN', 8, NOW()),
-- (9, 'emailnine@email.com', 'Password', 'Robert', 'Rodriguez', 'ADMIN', 9, NOW()),
-- (10, 'emailten@email.com', 'Password', 'Jennifer', 'Martinez', 'ADMIN', 10, NOW()),
-- (11, 'emaileleven@email.com', 'Password', 'William', 'Anderson', 'ADMIN', 11, NOW()),
-- (12, 'emailtwelve@email.com', 'Password', 'Patricia', 'Thomas', 'ADMIN', 12, NOW()),
-- (13, 'emailthirteen@email.com', 'Password', 'Charles', 'Jackson', 'ADMIN', 13, NOW()),
-- (14, 'emailfourteen@email.com', 'Password', 'Linda', 'White', 'ADMIN', 14, NOW()),
-- (15, 'emailfifteen@email.com', 'Password', 'Christopher', 'Harris', 'ADMIN', 15, NOW()),
-- (16, 'emailsixteen@email.com', 'Password', 'Barbara', 'Martin', 'ADMIN', 16, NOW()),
-- (17, 'emailseventeen@email.com', 'Password', 'Daniel', 'Thompson', 'ADMIN', 17, NOW()),
-- (18, 'emaileighteen@email.com', 'Password', 'Elizabeth', 'Garcia', 'ADMIN', 18, NOW()),
-- (19, 'emailnineteen@email.com', 'Password', 'Matthew', 'Martinez', 'ADMIN', 19, NOW()),
-- (20, 'emailtwenty@email.com', 'Password', 'Susan', 'Robinson', 'ADMIN', 20, NOW()),
-- (21, 'emailtwentyone@email.com', 'Password', 'Anthony', 'Clark', 'ADMIN', 21, NOW()),
-- (22, 'emailtwentytwo@email.com', 'Password', 'Dorothy', 'Rodriguez', 'ADMIN', 22, NOW()),
-- (23, 'emailtwentythree@email.com', 'Password', 'Mark', 'Lewis', 'ADMIN', 23, NOW()),
-- (24, 'emailtwentyfour@email.com', 'Password', 'Lisa', 'Lee', 'ADMIN', 24, NOW()),
-- (25, 'emailtwentyfive@email.com', 'Password', 'Donald', 'Walker', 'ADMIN', 25, NOW()),
-- (26, 'emailtwentysix@email.com', 'Password', 'Nancy', 'Hall', 'ADMIN', 26, NOW()),
-- (27, 'emailtwentyseven@email.com', 'Password', 'Paul', 'Allen', 'ADMIN', 27, NOW()),
-- (28, 'emailtwentyeight@email.com', 'Password', 'Karen', 'Young', 'ADMIN', 28, NOW()),
-- (29, 'emailtwentynine@email.com', 'Password', 'Andrew', 'Hernandez', 'ADMIN', 29, NOW()),
-- (30, 'emailthirty@email.com', 'Password', 'Betty', 'King', 'ADMIN', 30, NOW()),
-- (31, 'emailthirtyone@email.com', 'Password', 'Joshua', 'Wright', 'ADMIN', 31, NOW()),
-- (32, 'emailthirtytwo@email.com', 'Password', 'Helen', 'Lopez', 'ADMIN', 32, NOW()),
-- (33, 'emailthirtythree@email.com', 'Password', 'Kenneth', 'Hill', 'ADMIN', 33, NOW()),
-- (34, 'emailthirtyfour@email.com', 'Password', 'Sandra', 'Scott', 'ADMIN', 34, NOW()),
-- (35, 'emailthirtyfive@email.com', 'Password', 'Kevin', 'Green', 'ADMIN', 35, NOW()),
-- (36, 'emailthirtysix@email.com', 'Password', 'Donna', 'Adams', 'ADMIN', 36, NOW()),
-- (37, 'emailthirtyseven@email.com', 'Password', 'Brian', 'Baker', 'ADMIN', 37, NOW()),
-- (38, 'emailthirtyeight@email.com', 'Password', 'Carol', 'Gonzalez', 'ADMIN', 38, NOW()),
-- (39, 'emailthirtynine@email.com', 'Password', 'George', 'Nelson', 'ADMIN', 39, NOW()),
-- (40, 'emailforty@email.com', 'Password', 'Ruth', 'Carter', 'ADMIN', 40, NOW()),
-- (41, 'emailfortyone@email.com', 'Password', 'Edward', 'Mitchell', 'ADMIN', 41, NOW()),
-- (42, 'emailfortytwo@email.com', 'Password', 'Sharon', 'Perez', 'ADMIN', 42, NOW()),
-- (43, 'emailfortythree@email.com', 'Password', 'Ronald', 'Roberts', 'ADMIN', 43, NOW()),
-- (44, 'emailfortyfour@email.com', 'Password', 'Michelle', 'Turner', 'ADMIN', 44, NOW()),
-- (45, 'emailfortyfive@email.com', 'Password', 'Timothy', 'Phillips', 'ADMIN', 45, NOW()),
-- (46, 'emailfortysix@email.com', 'Password', 'Laura', 'Campbell', 'ADMIN', 46, NOW()),
-- (47, 'emailfortyseven@email.com', 'Password', 'Jason', 'Parker', 'ADMIN', 47, NOW()),
-- (48, 'emailfortyeight@email.com', 'Password', 'Sarah', 'Evans', 'ADMIN', 48, NOW()),
-- (49, 'emailfortynine@email.com', 'Password', 'Jeffrey', 'Edwards', 'ADMIN', 49, NOW()),
-- (50, 'emailfifty@email.com', 'Password', 'Kimberly', 'Collins', 'ADMIN', 50, NOW());

-- -- INSERT into jobs (id, title, description, location, employment_type, min_salary, max_salary, business_account_id, created_at) VALUES
-- -- (1, 'Software Engineer', 'Develop and maintain software applications.', 'New York, NY', 'FULL_TIME', 70000, 120000, 1, NOW()),
-- -- (2, 'Data Analyst', 'Analyze data to help make business decisions.', 'San Francisco, CA', 'FULL_TIME', 60000, 100000, 2, NOW()),
-- -- (3, 'Project Manager', 'Manage projects from initiation to closure.', 'Chicago, IL', 'CONTRACT', 80000, 130000, 3, NOW()),
-- -- (4, 'Marketing Specialist', 'Create and implement marketing strategies.', 'Los Angeles, CA', 'PART_TIME', 50000, 90000, 4, NOW()),
-- -- (5, 'Sales Representative', 'Sell products and services to customers.', 'Miami, FL', 'FULL_TIME', 40000, 80000, 5, NOW()),
-- -- (6, 'Customer Support Agent', 'Provide support to customers via phone and email.', 'Austin, TX', 'FULL_TIME', 35000, 60000, 6, NOW()),
-- -- (7, 'UX Designer', 'Design user interfaces for web and mobile applications.', 'Seattle, WA', 'CONTRACT', 70000, 110000, 7, NOW()),
-- -- (8, 'DevOps Engineer', 'Maintain and improve infrastructure and deployment processes.', 'Boston, MA', 'FULL_TIME', 90000, 140000, 8, NOW()),
-- -- (9, 'Content Writer', 'Create engaging content for blogs and social media.', 'Remote', 'FREELANCE', 30000, 50000, 9, NOW()),
-- -- (10, 'Financial Analyst', 'Analyze financial data and create reports.', 'New York, NY', 'FULL_TIME', 75000, 125000, 10, NOW()),
-- -- (11, 'HR Manager', 'Manage recruitment and employee relations.', 'Denver, CO', 'FULL_TIME', 60000, 100000, 11, NOW()),
-- -- (12, 'Business Analyst', 'Identify business needs and recommend solutions.', 'Atlanta, GA', 'CONTRACT', 70000, 120000, 12, NOW()),
-- -- (13, 'Graphic Designer', 'Create visual concepts for marketing materials.', 'Portland, OR', 'PART_TIME', 40000, 70000, 13, NOW()),
-- -- (14, 'IT Support Specialist', 'Provide technical support to employees.', 'Dallas, TX', 'FULL_TIME', 45000, 75000, 14, NOW()),
-- -- (15, 'Social Media Manager', 'Manage social media accounts and campaigns.', 'Remote', 'FREELANCE', 35000, 60000, 15, NOW()),
-- -- (16, 'Quality Assurance Tester', 'Test software applications for bugs and issues.', 'San Diego, CA', 'CONTRACT', 60000, 90000, 16, NOW()),
-- -- (17, 'Operations Manager', 'Oversee daily operations and improve efficiency.', 'Houston, TX', 'FULL_TIME', 80000, 130000, 17, NOW()),
-- -- (18, 'Product Manager', 'Define product vision and strategy.', 'San Francisco, CA', 'FULL_TIME', 90000, 150000, 18, NOW()),
-- -- (19, 'Research Scientist', 'Conduct research and experiments.', 'Cambridge, MA', 'FULL_TIME', 85000, 140000, 19, NOW()),
-- -- (20, 'Logistics Coordinator', 'Coordinate logistics and supply chain activities.', 'Chicago, IL', 'PART_TIME', 40000, 70000, 20, NOW()),
-- -- (21, 'Cybersecurity Analyst', 'Protect systems and networks from cyber threats.', 'New York, NY', 'FULL_TIME', 80000, 130000, 21, NOW()),
-- -- (22, 'Mobile App Developer', 'Develop mobile applications for iOS and Android.', 'Los Angeles, CA', 'CONTRACT', 70000, 120000, 22, NOW()),
-- -- (23, 'AI Engineer', 'Develop and implement AI models and algorithms.', 'San Francisco, CA', 'FULL_TIME', 100000, 160000, 23, NOW()),
-- -- (24, 'Blockchain Developer', 'Develop blockchain-based applications.', 'Remote', 'FREELANCE', 80000, 130000, 24, NOW()),
-- -- (25, 'Cloud Solutions Architect', 'Design and implement cloud solutions.', 'Seattle, WA', 'FULL_TIME', 110000, 170000, 25, NOW()),
-- -- (26, 'Big Data Engineer', 'Build and maintain big data infrastructure.', 'Austin, TX', 'FULL_TIME', 95000, 145000, 26, NOW()),
-- -- (27, 'IoT Developer', 'Develop Internet of Things applications.', 'Boston, MA', 'CONTRACT', 70000, 120000, 27, NOW()),
-- -- (28, 'VR Developer', 'Create virtual reality experiences.', 'San Diego, CA', 'PART_TIME', 60000, 100000, 28, NOW()),
-- -- (29, 'AR Developer', 'Develop augmented reality applications.', 'Remote', 'FREELANCE', 60000, 100000, 29, NOW()),
-- -- (30, 'Robotics Engineer', 'Design and build robotic systems.', 'Pittsburgh, PA', 'FULL_TIME', 90000, 140000, 30, NOW()),
-- -- (31, '3D Printing Specialist', 'Operate and maintain 3D printing equipment.', 'Detroit, MI', 'PART_TIME', 40000, 70000, 31, NOW()),
-- -- (32, 'Quantum Computing Researcher', 'Conduct research in quantum computing.', 'Cambridge, MA', 'FULL_TIME', 120000, 180000, 32, NOW()),
-- -- (33, 'Aerospace Engineer', 'Design and develop aircraft and spacecraft.', 'Houston, TX', 'FULL_TIME', 95000, 150000, 33, NOW()),
-- -- (34, 'Renewable Energy Consultant', 'Advise on renewable energy projects.', 'Denver, CO', 'CONTRACT', 80000, 130000, 34, NOW()),
-- -- (35, 'Smart Home Technician', 'Install and maintain smart home systems.', 'San Francisco, CA', 'PART_TIME', 40000, 70000, 35, NOW()),
-- -- (36, 'Wearable Tech Developer', 'Develop wearable technology devices.', 'Los Angeles, CA', 'FULL_TIME', 85000, 130000, 36, NOW()),
-- -- (37, 'E-commerce Manager', 'Manage online store operations.', 'New York, NY', 'FULL_TIME', 70000, 120000, 37, NOW()),
-- -- (38, 'Digital Marketing Specialist', 'Create and manage digital marketing campaigns.', 'Chicago, IL', 'CONTRACT', 60000, 100000, 38, NOW()),
-- -- (39, 'Social Media Strategist', 'Develop social media strategies to increase engagement.', 'Remote', 'FREELANCE', 40000, 70000, 39, NOW()),
-- -- (40, 'Content Marketing Manager', 'Oversee content marketing initiatives.', 'Austin, TX', 'FULL_TIME', 75000, 125000, 40, NOW()),
-- -- (41, 'SEO Specialist', 'Optimize websites for search engines.', 'Boston, MA', 'PART_TIME', 50000, 90000, 41, NOW()),
-- -- (42, 'PPC Manager', 'Manage pay-per-click advertising campaigns.', 'Seattle, WA', 'CONTRACT', 60000, 100000, 42, NOW()),
-- -- (43, 'Email Marketing Specialist', 'Create and manage email marketing campaigns.', 'Remote', 'FREELANCE', 40000, 70000, 43, NOW()),
-- -- (44, 'Affiliate Marketing Manager', 'Oversee affiliate marketing programs.', 'New York, NY', 'FULL_TIME', 60000, 100000, 44, NOW()),
-- -- (45, 'Influencer Marketing Coordinator', 'Coordinate influencer marketing campaigns.', 'Los Angeles, CA', 'PART_TIME', 40000, 70000, 45, NOW()),
-- -- (46, 'Web Developer', 'Build and maintain websites.', 'Chicago, IL', 'FULL_TIME', 70000, 120000, 46, NOW()),
-- -- (47, 'App Developer', 'Develop mobile and web applications.', 'San Francisco, CA', 'CONTRACT', 80000, 130000, 47, NOW()),
-- -- (48, 'Game Developer', 'Design and develop video games.', 'Austin, TX', 'FULL_TIME', 90000, 140000, 48, NOW()),
-- -- (49, 'UI/UX Designer', 'Design user interfaces and user experiences.', 'Remote', 'FREELANCE', 60000, 100000, 49, NOW()),
-- -- (50, 'Graphic Design Specialist', 'Create graphics for marketing and branding.', 'Portland, OR', 'PART_TIME', 40000, 70000, 50, NOW());

-- -- INSERT INTO tags (id, name, description, created_at) VALUES
-- -- (1, 'Software Development', 'Jobs related to software development and engineering.', NOW()),
-- -- (2, 'Data Science', 'Jobs in data analysis and data science.', NOW()),
-- -- (3, 'Project Management', 'Roles focused on managing projects and teams.', NOW()),
-- -- (4, 'Marketing', 'Positions in marketing and advertising.', NOW()),
-- -- (5, 'Sales', 'Jobs in sales and business development.', NOW()),
-- -- (6, 'Customer Support', 'Roles in customer service and support.', NOW()),
-- -- (7, 'Design', 'Jobs in UX/UI and graphic design.', NOW()),
-- -- (8, 'DevOps', 'Positions related to DevOps and infrastructure management.', NOW()),
-- -- (9, 'Content Creation', 'Roles in content writing and creation.', NOW()),
-- -- (10, 'Finance', 'Jobs in finance and accounting.', NOW()),
-- -- (11, 'Remote', 'Job is fully remote and can be done from anywhere.', NOW()),
-- -- (12, 'Hybrid', 'Job allows a mix of remote and in-office work.', NOW()),
-- -- (13, 'Contract', 'Temporary positions with a defined end date.', NOW()),
-- -- (14, 'Full-Time', 'Permanent positions with full-time hours.', NOW()),
-- -- (15, 'Part-Time', 'Positions with reduced hours compared to full-time.', NOW()),
-- -- (16, 'Internship', 'Entry-level positions for students or recent graduates.', NOW()),
-- -- (17, 'Freelance', 'Independent contractor roles with flexible hours.', NOW()),
-- -- (18, 'Cybersecurity', 'Jobs focused on protecting systems and data.', NOW()),
-- -- (19, 'AI & Machine Learning', 'Positions in artificial intelligence and machine learning.', NOW()),
-- -- (20, 'Blockchain', 'Roles related to blockchain technology and development.', NOW()),
-- -- (21, 'Cloud Computing', 'Jobs in cloud services and architecture.', NOW()),
-- -- (22, 'Big Data', 'Positions in big data technologies and analytics.', NOW()),
-- -- (23, 'IoT', 'Jobs related to Internet of Things technologies.', NOW()),
-- -- (24, 'Virtual Reality', 'Roles in virtual reality development.', NOW()),
-- -- (25, 'Augmented Reality', 'Positions in augmented reality applications.', NOW()),
-- -- (26, 'Robotics', 'Jobs in robotics engineering and development.', NOW()),
-- -- (27, '3D Printing', 'Roles related to 3D printing technology.', NOW()),
-- -- (28, 'Quantum Computing', 'Positions in quantum computing research and development.', NOW()),
-- -- (29, 'Aerospace', 'Jobs in aerospace engineering and technology.', NOW()),
-- -- (30, 'Renewable Energy', 'Roles focused on renewable energy solutions.', NOW()),
-- -- (31, 'Smart Home', 'Jobs in smart home technology and solutions.', NOW()),
-- -- (32, 'Wearable Technology', 'Positions in wearable tech development.', NOW()),
-- -- (33, 'E-commerce', 'Roles in online retail and e-commerce platforms.', NOW()),
-- -- (34, 'Digital Marketing', 'Jobs in digital marketing and online advertising.', NOW()),
-- -- (35, 'Social Media', 'Positions focused on social media management and strategy.', NOW()),
-- -- (36, 'SEO & SEM', 'Jobs in search engine optimization and marketing.', NOW()),
-- -- (37, 'Email Marketing', 'Roles in email marketing campaigns and strategies.', NOW()),
-- -- (38, 'Affiliate Marketing', 'Positions in affiliate marketing programs.', NOW()),
-- -- (39, 'Influencer Marketing', 'Jobs related to influencer partnerships and campaigns.', NOW()),
-- -- (40, 'Web Development', 'Roles in web development and programming.', NOW()),
-- -- (41, 'App Development', 'Positions in mobile app development.', NOW()),
-- -- (42, 'Game Development', 'Jobs in video game design and development.', NOW()),
-- -- (43, 'UI/UX Design', 'Roles in user interface and user experience design.', NOW()),
-- -- (44, 'Graphic Design', 'Jobs in graphic design and visual communication.', NOW()),
-- -- (45, 'HR & Recruitment', 'Positions in human resources and recruitment.', NOW()),
-- -- (46, 'Legal', 'Jobs in legal services and compliance.', NOW()),
-- -- (47, 'Healthcare', 'Roles in healthcare and medical services.', NOW()),
-- -- (48, 'Education', 'Positions in education and training.', NOW()),
-- -- (49, 'Non-Profit', 'Jobs in non-profit organizations and social causes.', NOW()),
-- -- (50, 'Logistics & Supply Chain', 'Roles in logistics and supply chain management.', NOW());

-- -- INSERT INTO job_tags (job_id, tag_id) VALUES
-- -- (1, 1), (1, 7), (2, 2), (2, 11), (3, 3), (3, 12), (4, 4), (4, 14),
-- -- (5, 5), (5, 15), (6, 6), (6, 16), (7, 7), (7, 8), (8, 8), (8, 9),
-- -- (9, 9), (9, 10), (10, 10), (10, 11), (11, 12), (11, 13), (12, 3),
-- -- (12, 14), (13, 7), (13, 15), (14, 6), (14, 16), (15, 4), (15, 17),
-- -- (16, 8), (16, 18), (17, 19), (17, 20), (18, 21), (18, 22),
-- -- (19, 23), (19, 24), (20, 25), (20, 26),
-- -- (21, 27), (21, 28), (22, 29), (22, 30), (23, 31), (23, 32),
-- -- (24, 33), (24, 34), (25, 35), (25, 36), (26, 37), (26, 38),
-- -- (27, 39), (27, 40), (28, 41), (28, 42), (29, 43), (29, 44),
-- -- (30, 45), (30, 46), (31, 47), (31, 48), (32, 49), (32, 50),
-- -- (33, 1), (33, 2), (34, 3), (34, 4), (35, 5), (35, 6),
-- -- (36, 7), (36, 8), (37, 9), (37, 10), (38, 11), (38, 12),
-- -- (39, 13), (39, 14), (40, 15), (40, 16), (41, 17), (41, 18),
-- -- (42, 19), (42, 20), (43, 21), (43, 22), (44, 23), (44, 24),
-- -- (45, 25), (45, 26), (46, 27), (46, 28), (47, 29), (47, 30),
-- -- (48, 31), (48, 32), (49, 33), (49, 34), (50, 35), (50, 36),
-- -- (1, 37), (2, 38), (3, 39), (4, 40), (5, 41), (6, 42),
-- -- (7, 43), (8, 44), (9, 45), (10, 46), (11, 47), (12, 48),
-- -- (13, 49), (14, 50), (15, 1), (16, 2), (17, 3), (18, 4),
-- -- (19, 5), (20, 6), (21, 7), (22, 8), (23, 9), (24, 10),
-- -- (25, 11), (26, 12), (27, 13), (28, 14), (29, 15), (30, 16),
-- -- (31, 17), (32, 18), (33, 19), (34, 20), (35, 21), (36, 22),
-- -- (37, 23), (38, 24), (39, 25), (40, 26), (41, 27), (42, 28),
-- -- (43, 29), (44, 30), (45, 31), (46, 32), (47, 33), (48, 34),
-- -- (49, 35), (49, 36), (50, 37), (50, 38), (1, 39), (2, 40), (3, 41), (4, 42),
-- -- (5, 43), (6, 44), (7, 45), (8, 46), (9, 47), (10, 48),
-- -- (11, 49), (12, 50);

-- -- INSERT into jobs (id, title, description, location, employment_type, min_salary, max_salary, business_account_id, created_at) VALUES
-- -- (51, 'Software Engineer', 'Develop and maintain software applications.', 'New York, NY', 'FULL_TIME', 70000, 120000, 54, NOW()),
-- -- (52, 'Data Scientist', 'Analyze and interpret complex data sets.', 'San Francisco, CA', 'FULL_TIME', 80000, 130000, 54, NOW()),
-- -- (53, 'Product Manager', 'Oversee product development and strategy.', 'Austin, TX', 'FULL_TIME', 90000, 140000, 54, NOW()),
-- -- (54, 'UX Designer', 'Design user-friendly interfaces and experiences.', 'Remote', 'FULL_TIME', 60000, 110000, 54, NOW()),
-- -- (55, 'DevOps Engineer', 'Manage and automate infrastructure and deployment.', 'Seattle, WA', 'FULL_TIME', 85000, 135000, 54, NOW()),
-- -- (56, 'Marketing Manager', 'Develop and execute marketing strategies.', 'Chicago, IL', 'FULL_TIME', 65000, 115000, 54, NOW()),
-- -- (57, 'Sales Executive', 'Drive sales and build customer relationships.', 'Boston, MA', 'FULL_TIME', 60000, 100000, 54, NOW()),
-- -- (58, 'Customer Support Specialist', 'Provide exceptional customer service and support.', 'Denver, CO', 'FULL_TIME', 40000, 70000, 54, NOW()),
-- -- (59, 'Content Writer', 'Create engaging content for various platforms.', 'Remote', 'FREELANCE', 30000, 60000, 54, NOW()),
-- -- (60, 'Financial Analyst', 'Analyze financial data and create reports.', 'New York, NY', 'FULL_TIME', 75000, 125000, 54, NOW());

-- -- INSERT INTO user_accounts (id, email, password, created_at) VALUES 
-- -- (2, 'user2@example.com', 'password2', NOW()),
-- -- (3, 'user3@example.com', 'password3', NOW()),
-- -- (6, 'user6@example.com', 'password6', NOW()),
-- -- (7, 'user7@example.com', 'password7', NOW()),
-- -- (8, 'user8@example.com', 'password8', NOW()),
-- -- (9, 'user9@example.com', 'password9', NOW()),
-- -- (10, 'user10@example.com', 'password10', NOW()),
-- -- (11, 'user11@example.com', 'password11', NOW()),
-- -- (12, 'user12@example.com', 'password12', NOW()),
-- -- (13, 'user13@example.com', 'password13', NOW()),
-- -- (14, 'user14@example.com', 'password14', NOW()),
-- -- (15, 'user15@example.com', 'password15', NOW()),
-- -- (16, 'user16@example.com', 'password16', NOW()),
-- -- (17, 'user17@example.com', 'password17', NOW()),
-- -- (18, 'user18@example.com', 'password18', NOW()),
-- -- (19, 'user19@example.com', 'password19', NOW()),
-- -- (20, 'user20@example.com', 'password20', NOW()),
-- -- (21, 'user21@example.com', 'password21', NOW()),
-- -- (22, 'user22@example.com', 'password22', NOW()),
-- -- (23, 'user23@example.com', 'password23', NOW()),
-- -- (24, 'user24@example.com', 'password24', NOW()),
-- -- (25, 'user25@example.com', 'password25', NOW()),
-- -- (26, 'user26@example.com', 'password26', NOW()),
-- -- (27, 'user27@example.com', 'password27', NOW()),
-- -- (28, 'user28@example.com', 'password28', NOW()),
-- -- (29, 'user29@example.com', 'password29', NOW()),
-- -- (30, 'user30@example.com', 'password30', NOW()),
-- -- (31, 'user31@example.com', 'password31', NOW()),
-- -- (32, 'user32@example.com', 'password32', NOW()),
-- -- (33, 'user33@example.com', 'password33', NOW()),
-- -- (34, 'user34@example.com', 'password34', NOW()),
-- -- (35, 'user35@example.com', 'password35', NOW()),
-- -- (36, 'user36@example.com', 'password36', NOW()),
-- -- (37, 'user37@example.com', 'password37', NOW()),
-- -- (38, 'user38@example.com', 'password38', NOW()),
-- -- (39, 'user39@example.com', 'password39', NOW()),
-- -- (40, 'user40@example.com', 'password40', NOW()),
-- -- (41, 'user41@example.com', 'password41', NOW()),
-- -- (42, 'user42@example.com', 'password42', NOW()),
-- -- (43, 'user43@example.com', 'password43', NOW()),
-- -- (44, 'user44@example.com', 'password44', NOW()),
-- -- (45, 'user45@example.com', 'password45', NOW()),
-- -- (46, 'user46@example.com', 'password46', NOW()),
-- -- (47, 'user47@example.com', 'password47', NOW()),
-- -- (48, 'user48@example.com', 'password48', NOW()),
-- -- (49, 'user49@example.com', 'password49', NOW()),
-- -- (50, 'user50@example.com', 'password50', NOW()),
-- -- (51, 'user51@example.com', 'password51', NOW()),
-- -- (52, 'user52@example.com', 'password52', NOW()),
-- -- (53, 'user53@example.com', 'password53', NOW()),
-- -- (54, 'user54@example.com', 'password54', NOW()),
-- -- (55, 'user55@example.com', 'password55', NOW()),
-- -- (56, 'user56@example.com', 'password56', NOW()),
-- -- (57, 'user57@example.com', 'password57', NOW()),
-- -- (58, 'user58@example.com', 'password58', NOW()),
-- -- (59, 'user59@example.com', 'password59', NOW()),
-- -- (60, 'user60@example.com', 'password60', NOW()),
-- -- (61, 'user61@example.com', 'password61', NOW()),
-- -- (62, 'user62@example.com', 'password62', NOW()),
-- -- (63, 'user63@example.com', 'password63', NOW()),
-- -- (64, 'user64@example.com', 'password64', NOW()),
-- -- (65, 'user65@example.com', 'password65', NOW()),
-- -- (66, 'user66@example.com', 'password66', NOW()),
-- -- (67, 'user67@example.com', 'password67', NOW()),
-- -- (68, 'user68@example.com', 'password68', NOW()),
-- -- (69, 'user69@example.com', 'password69', NOW()),
-- -- (70, 'user70@example.com', 'password70', NOW()),
-- -- (71, 'user71@example.com', 'password71', NOW()),
-- -- (72, 'user72@example.com', 'password72', NOW()),
-- -- (73, 'user73@example.com', 'password73', NOW()),
-- -- (74, 'user74@example.com', 'password74', NOW()),
-- -- (75, 'user75@example.com', 'password75', NOW()),
-- -- (76, 'user76@example.com', 'password76', NOW()),
-- -- (77, 'user77@example.com', 'password77', NOW()),
-- -- (78, 'user78@example.com', 'password78', NOW()),
-- -- (79, 'user79@example.com', 'password79', NOW()),
-- -- (80, 'user80@example.com', 'password80', NOW()),
-- -- (81, 'user81@example.com', 'password81', NOW()),
-- -- (82, 'user82@example.com', 'password82', NOW()),
-- -- (83, 'user83@example.com', 'password83', NOW()),
-- -- (84, 'user84@example.com', 'password84', NOW()),
-- -- (85, 'user85@example.com', 'password85', NOW()),
-- -- (86, 'user86@example.com', 'password86', NOW()),
-- -- (87, 'user87@example.com', 'password87', NOW()),
-- -- (88, 'user88@example.com', 'password88', NOW()),
-- -- (89, 'user89@example.com', 'password89', NOW()),
-- -- (90, 'user90@example.com', 'password90', NOW()),
-- -- (91, 'user91@example.com', 'password91', NOW()),
-- -- (92, 'user92@example.com', 'password92', NOW()),
-- -- (93, 'user93@example.com', 'password93', NOW()),
-- -- (94, 'user94@example.com', 'password94', NOW()),
-- -- (95, 'user95@example.com', 'password95', NOW()),
-- -- (96, 'user96@example.com', 'password96', NOW()),
-- -- (97, 'user97@example.com', 'password97', NOW()),
-- -- (98, 'user98@example.com', 'password98', NOW()),
-- -- (99, 'user99@example.com', 'password99', NOW()),
-- -- (100, 'user100@example.com', 'password100', NOW());
-- INSERT INTO tags (id, name, created_at) VALUES
-- (70, 'HTML/CSS', NOW()),
-- (71, 'JavaScript', NOW()),
-- (72, 'Python', NOW()),
-- (73, 'Java', NOW()),
-- (74, 'C#', NOW()),
-- (75, 'Ruby', NOW()),
-- (76, 'PHP', NOW()),
-- (77, 'Swift', NOW()),
-- (78, 'Kotlin', NOW()),
-- (79, 'Go', NOW()),
-- (80, 'TypeScript', NOW()),
-- (81, 'SQL', NOW()),
-- (82, 'NoSQL', NOW()),
-- (83, 'React', NOW()),
-- (84, 'Angular', NOW()),
-- (85, 'Vue.js', NOW()),
-- (86, 'Django', NOW()),
-- (87, 'Flask', NOW()),
-- (88, '.NET', NOW()),
-- (89, 'Spring Boot', NOW()),
-- (90, 'Ruby on Rails', NOW()),
-- (91, 'Laravel', NOW()),
-- (92, 'Symfony', NOW()),
-- (93, 'iOS Development', NOW()),
-- (94, 'Android Development', NOW()),
-- (95, 'Node.js', NOW()),
-- (96, 'Express.js', NOW()),
-- (97, 'GraphQL', NOW()),
-- (98, 'RESTful APIs', NOW()),
-- (99, 'Microservices', NOW()),
-- (100, 'Docker', NOW()),
-- (101, 'C++', NOW());

-- INSERT INTO job_tags (job_id, tag_id) VALUES
-- (51, 72), (51, 83), (51, 95),
-- (52, 72), (52, 81), (52, 97),
-- (53, 73), (53, 99), (53, 100),
-- (54, 70), (54, 83), (54, 85),
-- (55, 74), (55, 100), (55, 101),
-- (56, 71), (56, 80), (56, 84),
-- (57, 71), (57, 80), (57, 95),
-- (58, 70), (58, 71), (58, 81),
-- (59, 72), (59, 71), (59, 80),
-- (60, 73), (60, 81), (60, 82);

-- INSERT INTO interview_tips (id, interview_id, tip, created_at) VALUES
-- (1, 19, 'Research the company and its culture.', NOW()),
-- (2, 19, 'Practice common interview questions.', NOW()),
-- (3, 19, 'Dress appropriately for the interview.', NOW()),
-- (4, 19, 'Prepare examples of your past work.', NOW()),
-- (5, 19, 'Be ready to discuss your strengths and weaknesses.', NOW()),
-- (6, 19, 'Ask insightful questions about the role and company.', NOW()),
-- (7, 19, 'Arrive early to the interview location.', NOW()),
-- (8, 19, 'Bring multiple copies of your resume.', NOW()),
-- (9, 19, 'Follow up with a thank-you email after the interview.', NOW());

-- INSERT INTO user_projects (id, user_profile_id, project_name, project_description, project_link, created_at, year_completed) VALUES
-- (1, 2, 'Portfolio Website', 'A personal portfolio website showcasing my projects and skills.', 'https://portfolio.example.com', NOW(), 2023),
-- (2, 2, 'E-commerce Platform', 'Developed a full-featured e-commerce platform using Django and React.', 'https://ecommerce.example.com', NOW(), 2022),
-- (3, 2, 'Mobile Game', 'Created a mobile game using Unity and C#.', 'https://mobilegame.example.com', NOW(), 2021),
-- (4, 2, 'Blog Application', 'Built a blog application with user authentication and CRUD functionality.', 'https://blogapp.example.com', NOW(), 2023),
-- (5, 2, 'Chat Application', 'Developed a real-time chat application using Node.js and Socket.io.', 'https://chatapp.example.com', NOW(), 2022);

-- INSERT INTO business_profiles (id, business_account_id, summary, title, created_at) VALUES
-- (54, 54, 'Provides AWS support for media and enterainment', 'AWS Support Engineer', NOW());
-- (1, 1, 'Leading provider of innovative tech solutions.', 'Senior Software Engineer', NOW()),
-- (2, 2, 'Cutting-edge data analytics company.', 'Data Scientist', NOW()),
-- (3, 3, 'Global project management consultancy.', 'Project Manager', NOW()),
-- (4, 4, 'Creative marketing agency.', 'Marketing Manager', NOW()),
-- (5, 5, 'Top sales and business development firm.', 'Sales Executive', NOW()),
-- (6, 6, 'Customer-centric support services.', 'Customer Support Specialist', NOW()),
-- (7, 7, 'Innovative UX/UI design studio.', 'UX Designer', NOW()),
-- (8, 8, 'Leading DevOps solutions provider.', 'DevOps Engineer', NOW()),
-- (9, 9, 'Content creation and marketing experts.', 'Content Writer', NOW()),
-- (10, 10, 'Financial analysis and consulting firm.', 'Financial Analyst', NOW()),
-- (11, 11, 'Human resources and recruitment specialists.', 'HR Manager', NOW()),
-- (12, 12, 'Business analysis and strategy consultants.', 'Business Analyst', NOW()),
-- (13, 13, 'Graphic design and branding agency.', 'Graphic Designer', NOW()),
-- (14, 14, 'IT support and services provider.', 'IT Support Specialist', NOW()),
-- (15, 15, 'Social media management experts.', 'Social Media Manager', NOW()),
-- (16, 16, 'Quality assurance and testing services.', 'Quality Assurance Tester', NOW()),
-- (17, 17, 'Operations management consultancy.', 'Operations Manager', NOW()),
-- (18, 18, 'Product management and development firm.', 'Product Manager', NOW()),
-- (19, 19, 'Research and development in science and tech.', 'Research Scientist', NOW()),
-- (20, 20, 'Logistics and supply chain solutions.', 'Logistics Coordinator', NOW()),
-- (21, 21, 'Cybersecurity and data protection services.', 'Cybersecurity Analyst', NOW()),
-- (22, 22, 'Mobile app development company.', 'Mobile App Developer', NOW()),
-- (23, 23, 'AI and machine learning innovators.', 'AI Engineer', NOW()),
-- (24, 24, 'Blockchain technology solutions provider.', 'Blockchain Developer', NOW()),
-- (25, 25, 'Cloud computing and architecture experts.', 'Cloud Solutions Architect', NOW()),
-- (26, 26, 'Big data infrastructure and analytics firm.', 'Big Data Engineer', NOW()),
-- (27, 27, 'IoT technology development company.', 'IoT Developer', NOW()),
-- (28, 28, 'Virtual reality experiences creators.', 'VR Developer', NOW()),
-- (29, 29, 'Augmented reality applications developers.', 'AR Developer', NOW()),
-- (30, 30, 'Robotics engineering and innovation lab.', 'Robotics Engineer', NOW()),
-- (31, 31, '3D printing technology specialists.', '3D Printing Specialist', NOW()),
-- (32, 32, 'Quantum computing research institute.', 'Quantum Computing Researcher', NOW()),
-- (33, 33, 'Aerospace engineering and technology firm.', 'Aerospace Engineer', NOW()),
-- (34, 34, 'Renewable energy solutions consultancy.', 'Renewable Energy Consultant', NOW()),
-- (35, 35, 'Smart home technology providers.', 'Smart Home Technician', NOW()),
-- (36, 36, 'Wearable technology developers.', 'Wearable Tech Developer', NOW()),
-- (37, 37, 'Fintech solutions and digital banking services.', 'Fintech Specialist', NOW()),
-- (38, 38, 'E-commerce platform and online retail experts.', 'E-commerce Manager', NOW()),
-- (39, 39, 'Digital marketing and online advertising agency.', 'Digital Marketing Specialist', NOW()),
-- (40, 40, 'Social media strategy and management firm.', 'Social Media Strategist', NOW()),
-- (41, 41, 'SEO and SEM optimization services.', 'SEO Specialist', NOW()),
-- (42, 42, 'Email marketing campaigns and strategies experts.', 'Email Marketing Specialist', NOW()),
-- (43, 43, 'Affiliate marketing program managers.', 'Affiliate Marketing Manager', NOW()),
-- (44, 44, 'Influencer marketing and partnerships agency.', 'Influencer Marketing Coordinator', NOW()),
-- (45, 45, 'Web development and programming services.', 'Web Developer', NOW()),
-- (46, 46, 'Mobile app development and design firm.', 'App Developer', NOW()),
-- (47, 47, 'Video game design and development studio.', 'Game Developer', NOW()),
-- (48, 48, 'UI/UX design and user experience consultancy.', 'UI/UX Designer', NOW()),
-- (49, 49, 'Graphic design and visual communication agency.', 'Graphic Design Specialist', NOW()),
-- (50, 50, 'Human resources and recruitment services.', 'HR & Recruitment Specialist', NOW());

-- UPDATE user_profiles SET city = 'Seattle', state = 'WA', country = 'United States' WHERE id = 1;
-- UPDATE user_profiles SET city = 'San Francisco', state = 'CA', country = 'United States' WHERE id = 2;
-- UPDATE user_profiles SET city = 'New York', state = 'NY', country = 'United States' WHERE id = 3;
-- UPDATE user_profiles SET city = 'Los Angeles', state = 'CA', country = 'United States' WHERE id = 4;
-- UPDATE user_profiles SET city = 'Chicago', state = 'IL', country = 'United States' WHERE id = 5;
-- UPDATE user_profiles SET city = 'Houston', state = 'TX', country = 'United States' WHERE id = 6;
-- UPDATE user_profiles SET city = 'Toronto', province = 'ON', country = 'Canada' WHERE id = 7;
-- UPDATE user_profiles SET city = 'Vancouver', province = 'BC', country = 'Canada' WHERE id = 8;
-- UPDATE user_profiles SET city = 'Phoenix', state = 'AZ', country = 'United States' WHERE id = 9;
-- UPDATE user_profiles SET city = 'Philadelphia', state = 'PA', country = 'United States' WHERE id = 10;
-- UPDATE user_profiles SET city = 'San Antonio', state = 'TX', country = 'United States' WHERE id = 11;
-- UPDATE user_profiles SET city = 'San Diego', state = 'CA', country = 'United States' WHERE id = 12;
-- UPDATE user_profiles SET city = 'Dallas', state = 'TX', country = 'United States' WHERE id = 13;
-- UPDATE user_profiles SET city = 'San Jose', state = 'CA', country = 'United States' WHERE id = 14;
-- UPDATE user_profiles SET city = 'Austin', state = 'TX', country = 'United States' WHERE id = 15;
-- UPDATE user_profiles SET city = 'Jacksonville', state = 'FL', country = 'United States' WHERE id = 16;
-- UPDATE user_profiles SET city = 'Fort Worth', state = 'TX', country = 'United States' WHERE id = 17;
-- UPDATE user_profiles SET city = 'Columbus', state = 'OH', country = 'United States' WHERE id = 18;
-- UPDATE user_profiles SET city = 'Charlotte', state = 'NC', country = 'United States' WHERE id = 19;
-- UPDATE user_profiles SET city = 'Montreal', province = 'QC', country = 'Canada' WHERE id = 20;
-- UPDATE user_profiles SET city = 'Calgary', province = 'AB', country = 'Canada' WHERE id = 21;
-- UPDATE user_profiles SET city = 'Indianapolis', state = 'IN', country = 'United States' WHERE id = 22;
-- UPDATE user_profiles SET city = 'Denver', state = 'CO', country = 'United States' WHERE id = 23;
-- UPDATE user_profiles SET city = 'Washington', state = 'DC', country = 'United States' WHERE id = 24;
-- UPDATE user_profiles SET city = 'Boston', state = 'MA', country = 'United States' WHERE id = 25;
-- UPDATE user_profiles SET city = 'El Paso', state = 'TX', country = 'United States' WHERE id = 26;
-- UPDATE user_profiles SET city = 'Detroit', state = 'MI', country = 'United States' WHERE id = 27;
-- UPDATE user_profiles SET city = 'Nashville', state = 'TN', country = 'United States' WHERE id = 28;
-- UPDATE user_profiles SET city = 'Portland', state = 'OR', country = 'United States' WHERE id = 29;
-- UPDATE user_profiles SET city = 'Oklahoma City', state = 'OK', country = 'United States' WHERE id = 30;
-- UPDATE user_profiles SET city = 'Las Vegas', state = 'NV', country = 'United States' WHERE id = 31;
-- UPDATE user_profiles SET city = 'Louisville', state = 'KY', country = 'United States' WHERE id = 32;
-- UPDATE user_profiles SET city = 'Baltimore', state = 'MD', country = 'United States' WHERE id = 33;
-- UPDATE user_profiles SET city = 'Milwaukee', state = 'WI', country = 'United States' WHERE id = 34;
-- UPDATE user_profiles SET city = 'Albuquerque', state = 'NM', country = 'United States' WHERE id = 35;
-- UPDATE user_profiles SET city = 'Tucson', state = 'AZ', country = 'United States' WHERE id = 36;
-- UPDATE user_profiles SET city = 'Fresno', state = 'CA', country = 'United States' WHERE id = 37;
-- UPDATE user_profiles SET city = 'Mesa', state = 'AZ', country = 'United States' WHERE id = 38;
-- UPDATE user_profiles SET city = 'Sacramento', state = 'CA', country = 'United States' WHERE id = 39;
-- UPDATE user_profiles SET city = 'Atlanta', state = 'GA', country = 'United States' WHERE id = 40;
-- UPDATE user_profiles SET city = 'Kansas City', state = 'MO', country = 'United States' WHERE id = 41;
-- UPDATE user_profiles SET city = 'Colorado Springs', state = 'CO', country = 'United States' WHERE id = 42;
-- UPDATE user_profiles SET city = 'Omaha', state = 'NE', country = 'United States' WHERE id = 43;
-- UPDATE user_profiles SET city = 'Raleigh', state = 'NC', country = 'United States' WHERE id = 44;
-- UPDATE user_profiles SET city = 'Miami', state = 'FL', country = 'United States' WHERE id = 45;
-- UPDATE user_profiles SET city = 'Long Beach', state = 'CA', country = 'United States' WHERE id = 46;
-- UPDATE user_profiles SET city = 'Virginia Beach', state = 'VA', country = 'United States' WHERE id = 47;
-- UPDATE user_profiles SET city = 'Oakland', state = 'CA', country = 'United States' WHERE id = 48;
-- UPDATE user_profiles SET city = 'Minneapolis', state = 'MN', country = 'United States' WHERE id = 49;
-- UPDATE user_profiles SET city = 'Tulsa', state = 'OK', country = 'United States' WHERE id = 50;
-- UPDATE user_profiles SET city = 'Tampa', state = 'FL', country = 'United States' WHERE id = 51;
-- UPDATE user_profiles SET city = 'Arlington', state = 'TX', country = 'United States' WHERE id = 52;
-- UPDATE user_profiles SET city = 'New Orleans', state = 'LA', country = 'United States' WHERE id = 53;
-- UPDATE user_profiles SET city = 'Wichita', state = 'KS', country = 'United States' WHERE id = 54;
-- UPDATE user_profiles SET city = 'Cleveland', state = 'OH', country = 'United States' WHERE id = 55;
-- UPDATE user_profiles SET city = 'Tampa', state = 'FL', country = 'United States' WHERE id = 56;
-- UPDATE user_profiles SET city = 'Bakersfield', state = 'CA', country = 'United States' WHERE id = 57;
-- UPDATE user_profiles SET city = 'Aurora', state = 'CO', country = 'United States' WHERE id = 58;
-- UPDATE user_profiles SET city = 'Anaheim', state = 'CA', country = 'United States' WHERE id = 59;
-- UPDATE user_profiles SET city = 'Honolulu', state = 'HI', country = 'United States' WHERE id = 60;
-- UPDATE user_profiles SET city = 'Santa Ana', state = 'CA', country = 'United States' WHERE id = 61;
-- UPDATE user_profiles SET city = 'Corpus Christi', state = 'TX', country = 'United States' WHERE id = 62;
-- UPDATE user_profiles SET city = 'Riverside', state = 'CA', country = 'United States' WHERE id = 63;
-- UPDATE user_profiles SET city = 'Lexington', state = 'KY', country = 'United States' WHERE id = 64;
-- UPDATE user_profiles SET city = 'Stockton', state = 'CA', country = 'United States' WHERE id = 65;
-- UPDATE user_profiles SET city = 'Henderson', state = 'NV', country = 'United States' WHERE id = 66;
-- UPDATE user_profiles SET city = 'Saint Paul', state = 'MN', country = 'United States' WHERE id = 67;
-- UPDATE user_profiles SET city = 'St. Louis', state = 'MO', country = 'United States' WHERE id = 68;
-- UPDATE user_profiles SET city = 'Cincinnati', state = 'OH', country = 'United States' WHERE id = 69;
-- UPDATE user_profiles SET city = 'Pittsburgh', state = 'PA', country = 'United States' WHERE id = 70;
-- UPDATE user_profiles SET city = 'Greensboro', state = 'NC', country = 'United States' WHERE id = 71;
-- UPDATE user_profiles SET city = 'Lincoln', state = 'NE', country = 'United States' WHERE id = 72;
-- UPDATE user_profiles SET city = 'Plano', state = 'TX', country = 'United States' WHERE id = 73;
-- UPDATE user_profiles SET city = 'Anchorage', state = 'AK', country = 'United States' WHERE id = 74;
-- UPDATE user_profiles SET city = 'Orlando', state = 'FL', country = 'United States' WHERE id = 75;
-- UPDATE user_profiles SET city = 'Irvine', state = 'CA', country = 'United States' WHERE id = 76;
-- UPDATE user_profiles SET city = 'Newark', state = 'NJ', country = 'United States' WHERE id = 77;
-- UPDATE user_profiles SET city = 'Durham', state = 'NC', country = 'United States' WHERE id = 78;
-- UPDATE user_profiles SET city = 'Chula Vista', state = 'CA', country = 'United States' WHERE id = 79;
-- UPDATE user_profiles SET city = 'Toledo', state = 'OH', country = 'United States' WHERE id = 80;
-- UPDATE user_profiles SET city = 'Fort Wayne', state = 'IN', country = 'United States' WHERE id = 81;
-- UPDATE user_profiles SET city = 'St. Petersburg', state = 'FL', country = 'United States' WHERE id = 82;
-- UPDATE user_profiles SET city = 'Laredo', state = 'TX', country = 'United States' WHERE id = 83;
-- UPDATE user_profiles SET city = 'Jersey City', state = 'NJ', country = 'United States' WHERE id = 84;
-- UPDATE user_profiles SET city = 'Chandler', state = 'AZ', country = 'United States' WHERE id = 85;
-- UPDATE user_profiles SET city = 'Madison', state = 'WI', country = 'United States' WHERE id = 86;
-- UPDATE user_profiles SET city = 'Lubbock', state = 'TX', country = 'United States' WHERE id = 87;
-- UPDATE user_profiles SET city = 'Norfolk', state = 'VA', country = 'United States' WHERE id = 88;
-- UPDATE user_profiles SET city = 'Baton Rouge', state = 'LA', country = 'United States' WHERE id = 89;
-- UPDATE user_profiles SET city = 'Buffalo', state = 'NY', country = 'United States' WHERE id = 90;
-- UPDATE user_profiles SET city = 'Ottawa', province = 'ON', country = 'Canada' WHERE id = 91;
-- UPDATE user_profiles SET city = 'Edmonton', province = 'AB', country = 'Canada' WHERE id = 92;
-- UPDATE user_profiles SET city = 'Mississauga', province = 'ON', country = 'Canada' WHERE id = 93;
-- UPDATE user_profiles SET city = 'Winnipeg', province = 'MB', country = 'Canada' WHERE id = 94;
-- UPDATE user_profiles SET city = 'Quebec City', province = 'QC', country = 'Canada' WHERE id = 95;
-- UPDATE user_profiles SET city = 'Hamilton', province = 'ON', country = 'Canada' WHERE id = 96;
-- UPDATE user_profiles SET city = 'Brampton', province = 'ON', country = 'Canada' WHERE id = 97;
-- UPDATE user_profiles SET city = 'Surrey', province = 'BC', country = 'Canada' WHERE id = 98;
-- UPDATE user_profiles SET city = 'Laval', province = 'QC', country = 'Canada' WHERE id = 99;
-- UPDATE user_profiles SET city = 'Halifax', province = 'NS', country = 'Canada' WHERE id = 100;

-- UPDATE user_skills SET experience = 1 WHERE id = 691;
-- UPDATE user_skills SET experience = 2 WHERE id = 692;
-- UPDATE user_skills SET experience = 1 WHERE id = 693;
-- UPDATE user_skills SET experience = 4 WHERE id = 694;
-- UPDATE user_skills SET experience = 3 WHERE id = 695;
-- UPDATE user_skills SET experience = 5 WHERE id = 696;
-- UPDATE user_skills SET experience = 2 WHERE id = 697;
-- UPDATE user_skills SET experience = 7 WHERE id = 698;
-- UPDATE user_skills SET experience = 3 WHERE id = 699;
-- UPDATE user_skills SET experience = 6 WHERE id = 700;
-- UPDATE user_skills SET experience = 1 WHERE id = 701;
-- UPDATE user_skills SET experience = 9 WHERE id = 702;
-- UPDATE user_skills SET experience = 4 WHERE id = 703;
-- UPDATE user_skills SET experience = 8 WHERE id = 704;
-- UPDATE user_skills SET experience = 2 WHERE id = 705;
-- UPDATE user_skills SET experience = 5 WHERE id = 706;
-- UPDATE user_skills SET experience = 3 WHERE id = 707;

-- INSERT INTO conversations (id, participant_one_id, participant_two_id, participant_one_type, participant_two_type) VALUES
-- (1, 2, 54, 'USER', 'BUSINESS');
-- INSERT MESSAGES BETWEEN USERS AND BUSINESS PROFILES
-- INSERT FOR USER WITH ID 2 AND BUSINESS PROFILE ID OF 54
-- INSERT INTO messages (id, text, sender_id, receiver_id, timestamp, read, sender_type, receiver_type, conversation_id) VALUES
-- (1, 'Hello, I am interested in the Software Engineer position at your company. Could you provide more details about the role?', 2, 54, NOW() - INTERVAL '5 days', FALSE, 'USER', 'BUSINESS', 1),
-- (2, 'Thank you for reaching out! The Software Engineer position involves developing and maintaining software applications. We are looking for candidates with experience in Python and React. Would you like to schedule an interview?', 54, 2, NOW() - INTERVAL '4 days 18 hours', FALSE, 'BUSINESS', 'USER', 1),
-- (3, 'Yes, I would love to schedule an interview. Please let me know the available dates and times.', 2, 54, NOW() - INTERVAL '4 days 16 hours', FALSE, 'USER', 'BUSINESS', 1),
-- (4, 'Great! We have openings for interviews next week on Tuesday and Thursday at 10 AM or 2 PM. Which time works best for you?', 54, 2, NOW() - INTERVAL '3 days 14 hours', FALSE, 'BUSINESS', 'USER', 1),
-- (5, 'I can do Thursday at 10 AM. Please send me the details.', 2, 54, NOW() - INTERVAL '3 days 10 hours', FALSE, 'USER', 'BUSINESS', 1),
-- (6, 'Thursday at 10 AM is confirmed. We will send you a calendar invite with the interview details shortly. Looking forward to speaking with you!', 54, 2, NOW() - INTERVAL '2 days 8 hours', FALSE, 'BUSINESS', 'USER', 1);

-- INSERT INTO conversations (id, participant_one_id, participant_two_id, participant_one_type, participant_two_type) VALUES
-- (2, 2, 1, 'USER', 'BUSINESS');

-- INSERT MESSAGES BETWEEN USERS AND BUSINESS PROFILES
-- INSERT FOR USER WITH ID 2 AND BUSINESS PROFILE ID OF 1
-- INSERT INTO messages (id, text, sender_id, receiver_id, timestamp, read, sender_type, receiver_type, conversation_id) VALUES
-- (7, 'Hello, I would love to speak to you about an opening in our company?', 1, 2, NOW() - INTERVAL '5 days', FALSE, 'BUSINESS', 'USER', 2),
-- (8, 'Thank you for reaching out! I''m very interested in learning more about this opportunity.', 2, 1, NOW() - INTERVAL '4 days 20 hours', FALSE, 'USER', 'BUSINESS', 2),
-- (9, 'Great! The Software Engineer position involves developing and maintaining software applications. We are looking for candidates with experience in Python and React. Could you tell me about your background?', 1, 2, NOW() - INTERVAL '4 days 15 hours', FALSE, 'BUSINESS', 'USER', 2),
-- (10, 'I have 3 years of experience with Python and 2 years with React. I''ve worked on several full-stack applications and have experience with database design and API development.', 2, 1, NOW() - INTERVAL '4 days 10 hours', FALSE, 'USER', 'BUSINESS', 2),
-- (11, 'That sounds perfect for our needs! We also work with PostgreSQL and Spring Boot. Are you familiar with those technologies?', 1, 2, NOW() - INTERVAL '4 days 2 hours', FALSE, 'BUSINESS', 'USER', 2),
-- (12, 'Yes, I have experience with PostgreSQL and I''ve been learning Spring Boot recently. I''m always eager to expand my skill set.', 2, 1, NOW() - INTERVAL '3 days 18 hours', FALSE, 'USER', 'BUSINESS', 2),
-- (13, 'Excellent! Would you like to schedule an interview? We have openings next week on Tuesday and Thursday at 10 AM or 2 PM.', 1, 2, NOW() - INTERVAL '3 days 8 hours', FALSE, 'BUSINESS', 'USER', 2),
-- (14, 'I can do Thursday at 10 AM. That would work perfectly for me.', 2, 1, NOW() - INTERVAL '3 days 4 hours', FALSE, 'USER', 'BUSINESS', 2),
-- (15, 'Thursday at 10 AM is confirmed. We will send you a calendar invite with the interview details and meeting link shortly. Looking forward to speaking with you!', 1, 2, NOW() - INTERVAL '2 days 22 hours', FALSE, 'BUSINESS', 'USER', 2),
-- (16, 'Thank you so much! I received the calendar invite. I''m looking forward to our conversation and learning more about the role and your company culture.', 2, 1, NOW() - INTERVAL '2 days 18 hours', FALSE, 'USER', 'BUSINESS', 2);

-- UPDATE jobs SET description = 'Design, implement, and maintain scalable cloud solutions for enterprise environments. Collaborate with cross-functional teams to develop cloud strategies, migrate workloads, ensure security and high availability, and optimize performance across AWS, Azure, or GCP platforms.' WHERE id = 25;
-- UPDATE companies SET description = 'A leading provider of cloud computing solutions, specializing in scalable and secure infrastructure for businesses of all sizes. Our services include cloud migration, architecture design, and managed services across AWS, Azure, and Google Cloud platforms.' WHERE id = 25;

INSERT INTO business_accounts (id, email, password, created_at, account_type, first_name, last_name, company_id) VALUES
(55, 'jonsnow@email.com', 'winteriscoming', NOW(), 'RECRUITER', 'Jon', 'Snow', 57);

INSERT INTO business_profiles (id, business_account_id, summary, title, created_at) VALUES
(55, 55, 'Recruiter at Night''s Watch, seeking brave souls for the Wall.', 'Recruiter', NOW());

