package com.rizvi.jobee.helpers.AISchemas;

import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.rizvi.jobee.entities.InterviewPreparationQuestion;

import lombok.Data;

@Data
public class ReferenceToPreviousAnswer {
    @JsonPropertyDescription("Answer generated by AI for the interview question")
    private String aiAnswer;
    @JsonPropertyDescription("User's score for the answer")
    private Short userAnswerScore;
    @JsonPropertyDescription("Reason for the user's score")
    private String reasonForScore;
    @JsonPropertyDescription("Previous answer provided by the candidate")
    private String previousCandidateAnswer;
    @JsonPropertyDescription("New answer provided by the candidate")
    private String newCandidateAnswer;

    public ReferenceToPreviousAnswer(InterviewPreparationQuestion question, String previousCandidateAnswer,
            String newCandidateAnswer) {
        this.aiAnswer = question.getAiAnswer();
        this.userAnswerScore = question.getUserAnswerScore();
        this.reasonForScore = question.getReasonForScore();
        this.previousCandidateAnswer = previousCandidateAnswer;
        this.newCandidateAnswer = newCandidateAnswer;
    }

    public String toJsonString() {
        return """
                {"AIAnswer": "%s", "UserAnswerScore": %d, "ReasonForScore": "%s", "PreviousCandidateAnswer": "%s", "NewCandidateAnswer": "%s"}
                """
                .formatted(aiAnswer.replace("\"", "\\\""), userAnswerScore, reasonForScore.replace("\"", "\\\""),
                        previousCandidateAnswer.replace("\"", "\\\""), newCandidateAnswer.replace("\"", "\\\""));
    }
}
