package com.rizvi.jobee.enums;

public enum NotificationType {
    REJECTION,
    INTERVIEW_CANCELLED,
    INTERVIEW_COMPLETED,
    INTERVIEW_UPDATED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_RESCHEDULE_REQUESTED,
    INTERVIEW_RESULT,
    INTERVIEW_CONDUCTOR_REMOVED,
    INTERVIEW_CONDUCTOR_UPDATED,
    GENERAL,
    INTERVIEW_PREP_READY,
    INTERVIEW_REMINDER,
    AI_RESUME_REVIEW_COMPLETE,
    INTERVIEW_TO_CONDUCT_SCHEDULED,
    INTERVIEW_CREATED_SUCCESSFULLY,
    ADDED_TO_HIRING_TEAM
}
