package com.rizvi.jobee.enums;

public enum NotificationType {
    REJECTION,
    INTERVIEW_COMPLETED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_RESULT,
    GENERAL,
    INTERVIEW_PREP_READY,
    INTERVIEW_REMINDER,
    AI_RESUME_REVIEW_COMPLETE
}
