CREATE TABLE invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    email VARCHAR(255),
    phone_number VARCHAR(20),
    role VARCHAR(50) NOT NULL,
    invite_token VARCHAR(255) NOT NULL,
    company_code VARCHAR(50) NOT NULL,
    qr_code_url TEXT,
    invited_by BIGINT NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (invited_by) REFERENCES business_accounts(id) ON DELETE SET NULL ON UPDATE CASCADE
);