DROP TABLE IF EXISTS interview_rejections;
CREATE TABLE interview_rejections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason VARCHAR(255),
    feedback TEXT,
    interview_id BIGINT UNIQUE,
    application_id BIGINT UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview FOREIGN KEY (interview_id) REFERENCES interviews(id),
    CONSTRAINT fk_application FOREIGN KEY (application_id) REFERENCES applications(id)
);