CREATE TABLE reshedule_interview_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id BIGINT NOT NULL,
    reason TEXT,
    requested_time TIMESTAMP NOT NULL,
    start_time TIME NOT NULL, 
    timezone VARCHAR(100) NOT NULL,
    CONSTRAINT fk_interview FOREIGN KEY (interview_id) REFERENCES interviews(id)
);