CREATE TABLE interview_preperations_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_preperation_id BIGINT NOT NULL,
    review_rating INT NOT NULL CHECK (review_rating >= 1 AND review_rating <= 5),
    review_text TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview_preperation FOREIGN KEY (interview_preperation_id) REFERENCES interview_preparations(id) ON DELETE CASCADE
);
