-- Drop in correct order because of foreign key dependency
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS user_accounts;

-- Create user accounts table
CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create user profiles table
CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE,
    bio TEXT,
    profile_picture VARCHAR(255),
    FOREIGN KEY (account_id) REFERENCES user_accounts(id) ON DELETE CASCADE ON UPDATE CASCADE
);
