ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS company_type VARCHAR(50) NOT NULL DEFAULT 'SELF_SERVICE',
    ADD COLUMN IF NOT EXISTS verification_status VARCHAR(50) NOT NULL DEFAULT 'PENDING';

ALTER TABLE business_accounts
    ADD COLUMN IF NOT EXISTS account_type VARCHAR(50) NOT NULL DEFAULT 'RECRUITER';