ALTER TABLE business_profiles
ADD COLUMN profile_image_url VARCHAR(255),
ADD COLUMN verified BOOLEAN DEFAULT FALSE,
ADD COLUMN city VARCHAR(100),
ADD COLUMN state VARCHAR(100),
ADD COLUMN country VARCHAR(100);
