CREATE TABLE conversations (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_one_id BIGINT NOT NULL,
    participant_two_id BIGINT NOT NULL,
    participant_one_type VARCHAR(50) NOT NULL CHECK (participant_one_type IN ('USER', 'BUSINESS')),
    participant_two_type VARCHAR(50) NOT NULL CHECK (participant_two_type IN ('USER', 'BUSINESS')),
    last_message_id BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (participant_one_id, participant_two_id)
);

ALTER TABLE messages 
    ADD COLUMN conversation_id BIGINT,
    ADD FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE ON UPDATE CASCADE;