CREATE TABLE business_socials (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_account_id BIGINT NOT NULL,
    url VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    FOREIGN KEY (business_account_id) REFERENCES business_accounts(id) ON DELETE CASCADE
);