DROP TABLE IF EXISTS business_socials;

CREATE TABLE business_socials (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_profile_id BIGINT NOT NULL,
    url VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    FOREIGN KEY (business_profile_id) REFERENCES business_profiles(id) ON DELETE CASCADE
);